First version of Tracking
prime-slam/prime-slam pull request #2
Opened 2023-08-06 12:18 UTC by kirill-ivanov-a

- line tracking (LSD);
- point tracking (ORB, SIFT).

2023-09-27 11:25 UTC, anastasiia-kornilova commented
`module 'numpy' has no attribute 'bool'` -- error on numpy 1.24, freeze version in requirements

2023-10-18 10:32 UTC, anastasiia-kornilova requested changes

2023-10-18 10:32 UTC, anastasiia-kornilova commented on Dockerfile
> +    git \
Let's prefer to sort packages

2023-10-18 10:32 UTC, anastasiia-kornilova commented on README.md
> +  --save-cloud BOOL, -s BOOL
Where it will be saved? Not clear from readme

2023-10-18 10:32 UTC, anastasiia-kornilova commented on demo.py
> +        matcher=partial(match_descriptors, metric="hamming", max_ratio=0.8),
Open for discussion -- but maybe for such case it is better to specify exact library from which matching function is used like `skimage.match_descriptors`

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/geometry/pose.py
> +    def transformation(self) -> Transformation:
Maybe `.T()` operator could be shorter, I would support it also

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/geometry/pose.py
> +        self._transform_inv: Transformation = np.linalg.inv(self._transform)
Is this optimal to calculate inv each time?

At some moment I would switch to mrob.SE3 types (https://github.com/prime-slam/mrob/blob/master/src/geometry/SE3.cpp), they already have optimal representation inside. Let's add to issues

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/geometry/io.py
> +def read_poses(poses_path: Path, comment_symbol: str = "#") -> List[Pose]:
Poses can be presented in different ways, this one is in form of quaternions, it is better to specify

But since the next task is about data loaders, this fix can go here

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/geometry/util.py
> +    return vector if norm >= epsilon else vector
So in both cases you return vector, I don't understand what is the goal

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/metrics/pose_error.py
> +def angular_rotation_error(
This one module to be synced with TUM RGBD benchmark, let's add to issues

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/observation/filter/multiple_filter.py
> +class MultipleFilter(ObservationsFilter):
`FilterChain` seems better naming

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/observation/filter/point/point_clip_filter.py
> +class PointClipFilter(ObservationsFilter):
`PointClipFOVFilter` seems better

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/observation/filter/point/point_depth_filter.py
> +class PointDepthFilter(ObservationsFilter):
`PointNegativeDepthFilter`

2023-10-18 10:32 UTC, anastasiia-kornilova commented on prime_slam/sensor/rgbd.py
> +        self.bf = bf
bf is property of SLAM part, not the data itself, I would move it from here

2023-10-19 10:07 UTC, kirill-ivanov-a commented on demo.py
> +        matcher=partial(match_descriptors, metric="hamming", max_ratio=0.8),
Some algorithms use a custom matcher. For example, [SOLD2](https://github.com/cvg/SOLD2/blob/525dcd42134cc5981fbe8491d80cd4914b89ddec/sold2/model/line_matching.py#L12). Fixing a specific matcher from some library will make the code less flexible

2023-10-19 10:09 UTC, kirill-ivanov-a commented on prime_slam/geometry/pose.py
> +    def transformation(self) -> Transformation:
It seems it will be less expressive. Such an operator can be assumed to be a transpose, and also violates pep8

2023-10-19 10:15 UTC, kirill-ivanov-a commented on prime_slam/geometry/pose.py
> +        self._transform_inv: Transformation = np.linalg.inv(self._transform)
added to issues

2023-10-19 10:15 UTC, kirill-ivanov-a commented on prime_slam/geometry/io.py
> +def read_poses(poses_path: Path, comment_symbol: str = "#") -> List[Pose]:
added to issues

2023-10-19 10:16 UTC, kirill-ivanov-a commented on prime_slam/metrics/pose_error.py
> +def angular_rotation_error(
Why only with TUM?

2023-10-19 14:48 UTC, anastasiia-kornilova commented on prime_slam/metrics/pose_error.py
> +def angular_rotation_error(
Metrics kit from tum rgbd is mainly used now to do evaluations, it is reported in almost all papers, even with other datasets not only TUM RGBD
I mean, we need to check that we have the same metrics from it, to follow common convensions

2023-10-19 14:48 UTC, anastasiia-kornilova approved these changes

2023-10-23 06:58 UTC, merged